C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapatg (atgf2pywrap, s, t, p)
      external atg
      real s
      real t
      real p
      real atgf2pywrap, atg
      atgf2pywrap = atg(s, t, p)
      end


      subroutine f2pywrapeos8d (eos8df2pywrap, s, t, p0, drv)
      external eos8d
      real s
      real t
      real p0
      real drv(3,8)
      real eos8df2pywrap, eos8d
      eos8df2pywrap = eos8d(s, t, p0, drv)
      end


      subroutine f2pywrapsvan (svanf2pywrap, s, t, p0, sigma)
      external svan
      real s
      real t
      real p0
      real sigma
      real svanf2pywrap, svan
      svanf2pywrap = svan(s, t, p0, sigma)
      end


      subroutine f2pywraptheta (thetaf2pywrap, s, t0, p0, pr)
      external theta
      real s
      real t0
      real p0
      real pr
      real thetaf2pywrap, theta
      thetaf2pywrap = theta(s, t0, p0, pr)
      end

